export const mockTalents = [
  {
    _id: '1',
    name: 'John Doe',
    role: 'Actor',
    image: 'https://i.pravatar.cc/300?img=1',
    age: 28,
    price: 25,
    bio: 'Passionate actor with experience in theater and film.',
    hairColor: 'Brown',
    birthday: '1995-05-15',
    positiveKeywords: ['versatile', 'method acting', 'improv'],
    negativeKeywords: ['stunts', 'accents'],
    profileLink: 'https://example.com/johndoe',
    additionalPhotos: [
      'https://i.pravatar.cc/300?img=10',
      'https://i.pravatar.cc/300?img=20',
    ],
    isNew: true,
  },
  {
    _id: '2',
    name: 'Jane Smith',
    role: 'Model',
    image: 'https://i.pravatar.cc/300?img=2',
    age: 24,
    price: 0,
    hairColor: 'Blonde',
    birthday: '1999-08-22',
    positiveKeywords: ['runway', 'editorial', 'commercial'],
    profileLink: 'https://example.com/janesmith',
    additionalPhotos: [
      'https://i.pravatar.cc/300?img=30',
      'https://i.pravatar.cc/300?img=40',
    ],
    isNew: false,
  },
  {
    _id: '3',
    name: 'Mike Johnson',
    role: 'Musician',
    image: 'https://i.pravatar.cc/300?img=3',
    age: 32,
    price: 15,
    bio: 'Versatile musician specializing in guitar and vocals.',
    positiveKeywords: ['rock', 'blues', 'acoustic'],
    isNew: true,
  },
  {
    _id: '4',
    name: 'Emily Davis',
    role: 'Dancer',
    image: 'https://i.pravatar.cc/300?img=4',
    age: 26,
    price: 20,
    hairColor: 'Red',
    birthday: '1997-03-10',
    negativeKeywords: ['ballet', 'tap'],
    profileLink: 'https://example.com/emilydavis',
    isNew: false,
  },
  {
    _id: '5',
    name: 'Alex Thompson',
    role: 'Photographer',
    image: 'https://i.pravatar.cc/300?img=5',
    age: 29,
    price: 30,
    bio: "Capturing life's moments through the lens.",
    hairColor: 'Black',
    positiveKeywords: ['portrait', 'landscape', 'event'],
    additionalPhotos: [
      'https://i.pravatar.cc/300?img=50',
      'https://i.pravatar.cc/300?img=60',
    ],
    isNew: true,
  },
  {
    _id: '6',
    name: 'Sophia Lee',
    role: 'Singer',
    image: 'https://i.pravatar.cc/300?img=6',
    age: 27,
    price: 0,
    birthday: '1996-11-30',
    positiveKeywords: ['pop', 'R&B', 'soul'],
    negativeKeywords: ['rock', 'metal'],
    profileLink: 'https://example.com/sophialee',
    isNew: false,
  },
  {
    _id: '7',
    name: 'Daniel Brown',
    role: 'Comedian',
    image: 'https://i.pravatar.cc/300?img=7',
    age: 35,
    price: 40,
    bio: 'Bringing laughter to audiences everywhere.',
    hairColor: 'Brown',
    birthday: '1988-07-19',
    positiveKeywords: ['stand-up', 'improv', 'sketch'],
    additionalPhotos: [
      'https://i.pravatar.cc/300?img=70',
      'https://i.pravatar.cc/300?img=80',
    ],
    isNew: true,
  },
  {
    _id: '8',
    name: 'Olivia Martinez',
    role: 'Artist',
    image: 'https://i.pravatar.cc/300?img=8',
    age: 31,
    price: 0,
    hairColor: 'Black',
    positiveKeywords: ['painting', 'sculpture', 'mixed media'],
    profileLink: 'https://example.com/oliviamartinez',
    isNew: false,
  },
  {
    _id: '9',
    name: 'Ethan Wilson',
    role: 'Voice Actor',
    image: 'https://i.pravatar.cc/300?img=9',
    age: 33,
    price: 18,
    bio: 'Bringing characters to life through voice.',
    birthday: '1990-02-14',
    positiveKeywords: ['animation', 'video games', 'commercials'],
    negativeKeywords: ['screaming', 'singing'],
    additionalPhotos: [
      'https://i.pravatar.cc/300?img=90',
      'https://i.pravatar.cc/300?img=100',
    ],
    isNew: true,
  },
  {
    _id: '10',
    name: 'Isabella Garcia',
    role: 'Makeup Artist',
    image: 'https://i.pravatar.cc/300?img=11',
    age: 28,
    price: 22,
    hairColor: 'Brown',
    positiveKeywords: ['bridal', 'special effects', 'editorial'],
    profileLink: 'https://example.com/isabellagarcia',
    isNew: false,
  },
  {
    _id: '11',
    name: 'Liam Taylor',
    role: 'Stuntman',
    image: 'https://i.pravatar.cc/300?img=12',
    age: 29,
    price: 0,
    bio: 'Pushing the limits of physical performance.',
    birthday: '1994-09-03',
    positiveKeywords: ['martial arts', 'parkour', 'wire work'],
    negativeKeywords: ['heights'],
    isNew: true,
    additionalPhotos: [
      'https://i.pravatar.cc/300?img=121',
      'https://i.pravatar.cc/300?img=122',
      'https://i.pravatar.cc/300?img=123',
    ],
  },
  {
    _id: '12',
    name: 'Ava Robinson',
    role: 'Fashion Designer',
    image: 'https://i.pravatar.cc/300?img=13',
    age: 33,
    price: 0,
    hairColor: 'Blonde',
    positiveKeywords: ['avant-garde', 'sustainable', 'streetwear'],
    profileLink: 'https://example.com/avarobinson',
    isNew: false,
  },
  {
    _id: '13',
    name: 'Noah Clark',
    role: 'DJ',
    image: 'https://i.pravatar.cc/300?img=14',
    age: 26,
    price: 28,
    bio: 'Creating unforgettable experiences through music.',
    positiveKeywords: ['electronic', 'hip-hop', 'house'],
    negativeKeywords: ['country'],
    additionalPhotos: [
      'https://i.pravatar.cc/300?img=141',
      'https://i.pravatar.cc/300?img=142',
    ],
    isNew: true,
  },
  {
    _id: '14',
    name: 'Emma White',
    role: 'Yoga Instructor',
    image: 'https://i.pravatar.cc/300?img=15',
    age: 30,
    price: 12,
    hairColor: 'Brown',
    birthday: '1993-12-05',
    positiveKeywords: ['vinyasa', 'meditation', 'wellness'],
    profileLink: 'https://example.com/emmawhite',
    isNew: false,
  },
  {
    _id: '15',
    name: 'James Anderson',
    role: 'Magician',
    image: 'https://i.pravatar.cc/300?img=16',
    age: 38,
    price: 35,
    bio: 'Blending illusion and reality for mind-bending performances.',
    positiveKeywords: ['close-up magic', 'mentalism', 'stage shows'],
    additionalPhotos: [
      'https://i.pravatar.cc/300?img=161',
      'https://i.pravatar.cc/300?img=162',
    ],
    isNew: true,
  },
  {
    _id: '16',
    name: 'Mia Johnson',
    role: 'Choreographer',
    image: 'https://i.pravatar.cc/300?img=17',
    age: 32,
    price: 26,
    hairColor: 'Black',
    birthday: '1991-06-18',
    positiveKeywords: ['contemporary', 'hip-hop', 'ballet'],
    negativeKeywords: ['tap'],
    isNew: false,
  },
  {
    _id: '17',
    name: 'Benjamin Lee',
    role: 'Graphic Designer',
    image: 'https://i.pravatar.cc/300?img=18',
    age: 28,
    price: 0,
    bio: 'Creating visual stories that captivate and inspire.',
    positiveKeywords: ['branding', 'UI/UX', 'illustration'],
    profileLink: 'https://example.com/benjaminlee',
    additionalPhotos: [
      'https://i.pravatar.cc/300?img=181',
      'https://i.pravatar.cc/300?img=182',
    ],
    isNew: true,
  },
  {
    _id: '18',
    name: 'Charlotte Davis',
    role: 'Voiceover Artist',
    image: 'https://i.pravatar.cc/300?img=19',
    age: 29,
    price: 16,
    hairColor: 'Red',
    birthday: '1994-04-22',
    positiveKeywords: ['audiobooks', 'e-learning', 'podcasts'],
    negativeKeywords: ['accents'],
    isNew: false,
  },
  {
    _id: '19',
    name: 'William Turner',
    role: 'Sculptor',
    image: 'https://i.pravatar.cc/300?img=20',
    age: 42,
    price: 45,
    bio: 'Transforming raw materials into thought-provoking art.',
    positiveKeywords: ['metal', 'stone', 'wood'],
    profileLink: 'https://example.com/williamturner',
    additionalPhotos: [
      'https://i.pravatar.cc/300?img=201',
      'https://i.pravatar.cc/300?img=202',
    ],
    isNew: true,
  },
  {
    _id: '20',
    name: 'Sophia Chen',
    role: 'Calligrapher',
    image: 'https://i.pravatar.cc/300?img=21',
    age: 35,
    price: 24,
    hairColor: 'Black',
    birthday: '1988-09-15',
    positiveKeywords: ['traditional', 'modern', 'hand lettering'],
    negativeKeywords: ['digital'],
    profileLink: 'https://example.com/sophiachen',
    isNew: false,
  },
];